import NextHead from 'next/head'

const Head = ({ title }) => {
	const pageTitle = `קיצור כתובת | ${title}`

	return (
		<NextHead>
			<title>{pageTitle}</title>
			<meta
				name='description'
				content='Generated by create next app'
			/>
			<link
				rel='icon'
				href='/favicon.ico'
			/>
		</NextHead>
	)
}

export default Head
